import { EventCardProps } from "@/types/events";

export const eventList: EventCardProps[] = [
  {
    id: "event-01",
    title: "Slum Art World Skills Day Exhibition",
    date: "July 18, 2020",
    location: "Lagos, Nigeria",
    imageSrc: "https://www.gocycle.ng/_next/image?q=75&url=%2Fimages%2Fadetunwase-adenle.jpg&w=384",
    url: "https://guardian.ng/saturday-magazine/slum-art-foundation-marks-world-skills-day-with-art-exhibition/",
  },
  {
    id: "event-02",
    title: "My Freedom Day Art Project",
    date: "March 2019",
    location: "Ijora-Badia, Lagos",
    imageSrc: "https://www.gocycle.ng/_next/image?q=75&url=%2Fimages%2Fadetunwase-adenle.jpg&w=384",
    url: "https://guardian.ng/saturday-magazine/slum-art-foundation-marks-my-freedom-day-with-exhibition/",
  },
  {
    id: "event-03",
    title: "Feature Earth AI Creators Programme",
    date: "June 2026",
    location: "Nigeria",
    imageSrc: "https://www.gocycle.ng/_next/image?q=75&url=%2Fimages%2Fadetunwase-adenle.jpg&w=384",
    url: "https://guardian.ng/technology/animation-hub-launches-feature-earth-ai-creators-programme/",
  },
  {
    id: "event-04",
    title: "Slum Art Community Exhibition",
    date: "2026 (reported)",
    location: "Freedom Park, Lagos",
    imageSrc: "https://cdn.guardian.ng/wp-content/uploads/2020/07/Slum.jpg",
    url: "https://guardian.ng/art/when-a-child-picks-up-a-brush-a-community-begins-to-heal/",
  },
  {
    id: "event-05",
    title: "GoCycle Lagos Scale-up",
    date: "Current initiative",
    location: "Lagos, Nigeria",
    imageSrc: "https://cdn.guardian.ng/wp-content/uploads/2020/07/Slum.jpg",
    url: "https://www.gocycle.ng/about",
  },
  {
    id: "event-06",
    title: "Slum Art Pet Bottle School",
    date: "Established 2018",
    location: "Ijora-Badia, Lagos",
    imageSrc: "https://cdn.guardian.ng/wp-content/uploads/2020/07/Slum.jpg",
    url: "https://guardian.ng/saturday-magazine/slum-art-foundation-marks-world-skills-day-with-art-exhibition/",
  },
  {
    id: "event-07",
    title: "Community Art Exhibition",
    date: "July 2020",
    location: "Online and Lagos, Nigeria",
    imageSrc: "https://cdn.guardian.ng/wp-content/uploads/2020/07/Slum.jpg",
    url: "https://guardian.ng/saturday-magazine/slum-art-foundation-marks-world-skills-day-with-art-exhibition/",
  },
  {
    id: "event-08",
    title: "Slum Art Community Programmes",
    date: "Founded 2017",
    location: "Lagos, Nigeria",
    imageSrc: "https://cdn.guardian.ng/wp-content/uploads/2020/07/Slum.jpg",
    url: "https://slumart.org/",
  },
];
